# Generated by Django 4.0 on 2021-12-27 15:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('covidtracker', '0002_covidcase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='hour',
            new_name='endingHour',
        ),
        migrations.RemoveField(
            model_name='covidcase',
            name='vaccinated',
        ),
        migrations.AddField(
            model_name='lecture',
            name='startingHour',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
