# Generated by Django 4.0 on 2021-12-27 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidtracker', '0003_rename_hour_lecture_endinghour_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='endingHour',
            new_name='hour',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='startingHour',
        ),
    ]
