# Generated by Django 4.0 on 2022-01-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidtracker', '0006_alter_lecture_endinghour_alter_lecture_startinghour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='endingHour',
            field=models.TimeField(verbose_name='Ending Hour'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='startingHour',
            field=models.TimeField(verbose_name='Starting Hour'),
        ),
    ]
