# Generated by Django 4.0 on 2022-01-06 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covidtracker', '0008_course_remove_lecture_endinghour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='amphitheater',
        ),
        migrations.AddField(
            model_name='course',
            name='amphitheater',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='covidtracker.amphitheater'),
            preserve_default=False,
        ),
    ]
