# Generated by Django 4.0.2 on 2022-02-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidtracker', '0009_remove_lecture_amphitheater_course_amphitheater'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lessonType',
            field=models.CharField(choices=[(1, 'Υποχρεωτικό'), (2, 'Επιλογής')], default=1, max_length=30, verbose_name='Τύπος μαθήματος'),
            preserve_default=False,
        ),
    ]
