# Generated by Django 4.0.2 on 2022-02-21 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidtracker', '0011_alter_course_lessontype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lessonType',
            field=models.CharField(choices=[('Υποχρεωτικό', 'Υποχρεωτικό'), ('Επιλογής', 'Επιλογής')], max_length=30, verbose_name='Τύπος μαθήματος'),
        ),
    ]
