# Generated by Django 4.0.3 on 2022-03-11 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('covidtracker', '0012_alter_course_lessontype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amphitheater',
            options={'verbose_name': 'Αμφιθέατρο', 'verbose_name_plural': 'Αμφιθέατρα'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Στοιχεία διάλεξης (χωρίς ημερομηνία)', 'verbose_name_plural': 'Στοιχεία διαλέξεων (χωρίς ημερομηνία)'},
        ),
        migrations.AlterModelOptions(
            name='covidcase',
            options={'verbose_name': 'Κρούσμα', 'verbose_name_plural': 'Κρούσματα'},
        ),
        migrations.AlterModelOptions(
            name='lecture',
            options={'verbose_name': 'Ημερομηνία διάλεξης', 'verbose_name_plural': 'Ημερομηνία διαλέξεων'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Θέση φοιτητή', 'verbose_name_plural': 'Θέσεις φοιτητών'},
        ),
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.CharField(default='Κλεοπάτρα Μπαρδάκη', max_length=40, verbose_name='Καθηγητής'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='amphitheater',
            name='capacity',
            field=models.IntegerField(verbose_name='Χωρητικότητα'),
        ),
        migrations.AlterField(
            model_name='amphitheater',
            name='floor',
            field=models.IntegerField(verbose_name='Οροφος'),
        ),
        migrations.AlterField(
            model_name='amphitheater',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Ονομα'),
        ),
        migrations.AlterField(
            model_name='course',
            name='amphitheater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidtracker.amphitheater', verbose_name='Αμφιθέατρο'),
        ),
        migrations.AlterField(
            model_name='course',
            name='endingHour',
            field=models.TimeField(verbose_name='Ωρα λήξης'),
        ),
        migrations.AlterField(
            model_name='course',
            name='lesson',
            field=models.CharField(max_length=40, verbose_name='Μάθημα'),
        ),
        migrations.AlterField(
            model_name='course',
            name='startingHour',
            field=models.TimeField(verbose_name='Ωρα έναρξης'),
        ),
        migrations.AlterField(
            model_name='covidcase',
            name='date',
            field=models.DateField(verbose_name='Ημερομηνία'),
        ),
        migrations.AlterField(
            model_name='covidcase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Αριθμός μητρώου'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidtracker.course', verbose_name='Μάθημα'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='date',
            field=models.DateField(verbose_name='Ημερομηνία'),
        ),
        migrations.AlterField(
            model_name='position',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidtracker.lecture', verbose_name='Στοιχεία διάλεξης'),
        ),
        migrations.AlterField(
            model_name='position',
            name='positionNumber',
            field=models.IntegerField(verbose_name='Αριθμός θέσης'),
        ),
        migrations.AlterField(
            model_name='position',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Αριθμός μητρώου'),
        ),
    ]
