apiVersion: v1
kind: ConfigMap
metadata:
  name: thesis-config
data:
  DJANGO_DEBUG: "False"
  DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,thesis.local"
  DJANGO_DATABASE_NAME: "/data/db.sqlite3"
  DJANGO_MEDIA_ROOT: "/data/images"
  DJANGO_STATIC_ROOT: "/app/assets"
  PYTHONDONTWRITEBYTECODE: "1"
  PYTHONUNBUFFERED: "1"
