apiVersion: v1
kind: ConfigMap
metadata:
  name: thesis-config
data:
  DJANGO_DEBUG: "False"
  DJANGO_ALLOWED_HOSTS: "localhost,127.0.0.1,thesis.local"
  DJANGO_DATABASE_NAME: "/data/db.sqlite3"
  DJANGO_MEDIA_ROOT: "/data/images"
  DJANGO_STATIC_ROOT: "/app/assets"
  PYTHONDONTWRITEBYTECODE: "1"
  PYTHONUNBUFFERED: "1"
  DJANGO_SECURE_SSL_REDIRECT: "False"
  DJANGO_SECURE_HSTS_SECONDS: "0"
  DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS: "False"
  DJANGO_SECURE_HSTS_PRELOAD: "False"
  DJANGO_SESSION_COOKIE_SECURE: "False"
  DJANGO_CSRF_COOKIE_SECURE: "False"
